### ISSUE TITLE
dev: Check seqno after reconnect writer session

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-go-sdk#480]
Customer code can send messages with internal pack and different topic seq-no numbers.

For example one thread can send messages:
```yaml
- seqno: 3
  content: 1,2,3
- seqno: 10
  content: 4,5,6,7,8,9,10
```

and other thread:
```yaml
- seqno: 2:
   content: 1,2
- seqno: 5
   content: 3,4,5
```

mix of the thread will duplicate customer's content.

topic writer must have retry-policy for that case and check seqno after reconnect by default: if seqno changed between reconnects - writer should stop write and return error by default.
