### ISSUE TITLE
dev: Switch golangci config from opt-in linters to opt-out

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#738]
For example https://gist.github.com/asmyasnikov/eccb01b3e454afe9391f892183b26ecb

**Comment by Albitko** [comment]
Is it meant to replace 
```yaml
disable-all: true
enable:
   ...
```
 with 
```yaml
enable-all: true
disable:
   ...
```
?
